### ISSUE TITLE
SideBars

### ISSUE THREAD

**Issue by WildCardSys** [lezzthanthree/Needy-Streamer-Overload#16]
Every time i try to configure the social media pic with the arrows, the side bars warp, one to the next screen and the other to the opposite side from the original screen

**Comment by lezzthanthree** [comment]
I have replicated the problem and it did goes to the opposite side of the original screen.
![image](https://github.com/lezzthanthree/Needy-Streamer-Overload/assets/63889032/6bed5e69-5f9c-41c3-9998-79c88db4f8b9)

This is because it gets the screen width of the primary skin and sets the top-left coordinates there, causing the skin to move to the next screen.
https://github.com/lezzthanthree/Needy-Streamer-Overload/blob/dde7b88e555e3c8f8f8b5af25585549cdd4f3041/Sidebars/Right/Sidebars.ini#L3

**Comment by lezzthanthree** [comment]
The bug has now been fixed by changing the anchoring to the top-right.
https://github.com/lezzthanthree/Needy-Streamer-Overload/blob/1374bc332d046eeee33b4114660db61ed2847fe2/Sidebars/Right/Sidebars.ini#L3
